import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";
import Footer from "@/components/ui/footer/Footer";
import { AuthProvider } from "@/features/auth/context/auth-provider";
import { UnifiedDialogProvider } from "@/features/dialogs/context/unified-dialog-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gunpla Model Expo",
  description: "Generated by HobbyCity",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="flex flex-col text-white-site">
        <UnifiedDialogProvider>
          <AuthProvider>
            <main className="min-h-screen">{children}</main>
            <Footer socialNetworks={[{
                type: "facebook",
                name: "Facebook",
                url: "#"
              },{
                type: "web",
                name: "Website",
                url: "#"
              }]} />
          </AuthProvider>
        </UnifiedDialogProvider>
      </body>
    </html>
  );
}
