import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";
import FloatingToolbar from "@/components/ui/toolbar/FloatingToolbar";
import Footer from "@/components/ui/footer/Footer";
import { AuthProvider } from "@/features/auth/context/auth-provider";
import { ErrorDialogProvider } from "@/features/error-dialog/context/error-dialog-provider";
import { LoadingDialogProvider } from "@/features/loading-dialog/context/loading-dialog-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col text-white-site">
        <LoadingDialogProvider>
          <ErrorDialogProvider>
            <AuthProvider>
              <FloatingToolbar />
              <main className="flex-1">{children}</main>
              <Footer socialNetworks={[{
                  type: "facebook",
                  name: "Facebook",
                  url: "#"
                },{
                  type: "web",
                  name: "Website",
                  url: "#"
                }]} />
            </AuthProvider>
          </ErrorDialogProvider>
        </LoadingDialogProvider>
      </body>
    </html>
  );
}
